// Restore-on-load: render a #share= answer or a #dash= dashboard captured in
// the URL fragment, plus the invalid-link error states. Extracted verbatim.
// Drives the app's own render path (createTurnBlock -> renderChart/renderTable/
// renderCitations/renderTrace ...) so a restored view is pixel-identical to a
// live one. maybeRestoreFromFragment() is invoked once from boot on load.
import type { TurnBlock } from './state';
import {
  consoleEl, allTurns, liveChartTurns, newConvoBtn, composerQ,
  dashView, dashViewTitle, dashViewBack, dashViewBody,
} from './state';
import { rowsToCSV } from '../tools';
import { decodeShareState, type ShareStateV1 } from '../share';
import { decodeDashShare, materializeSharedDashboard, type DashShareV1 } from '../dashboard-share';
import { fmtShareDate } from './dom';
import { createTurnBlock, renderQuestion, setStatus } from './turns';
import { renderTrace, renderFiles } from './trace';
import { renderChart } from './charts';
import { renderTable, renderCitations, renderFinding, renderVerification, renderSharedVerification, renderRunningTotal } from './evidence';
import { renderSharedDashboard, resetSharedDashState } from './dashboards-view';


// Where a restored answer came from. Both are frozen snapshots rendered with no
// key and no agent run; they differ only in what the banner must disclose.
//   'shared' — arrived in a #share= fragment, generated by whoever made the link.
//   'demo'   — shipped with the app as a worked example (see lib/demos.ts).
export type RestoreMode = 'shared' | 'demo';

export function renderShareBanner(tb: TurnBlock, state: ShareStateV1, mode: RestoreMode = 'shared') {
  const el = tb.shareBanner;
  el.textContent = '';
  el.style.display = 'block';
  const lead = document.createElement('span');
  lead.className = 'ch-share-banner-lead';
  // A demo says "example", never "verified just now": the numbers are real and
  // fetched, but they were fetched when the demo was generated, not on this
  // page load. Same disclosure discipline as a shared link.
  lead.textContent =
    mode === 'demo'
      ? `Example answer — real data, fetched ${fmtShareDate(state.ts)} · your own questions run live`
      : `Shared answer — generated ${fmtShareDate(state.ts)} · data as fetched then` +
        (state.lossy ? ' · showing charted data only' : '');
  const link = document.createElement('a');
  link.className = 'ch-share-banner-link';
  if (mode === 'demo') {
    // The composer is already on screen for a demo (nothing to reload away
    // from), so the link just puts the cursor in it.
    link.href = '#';
    link.textContent = 'ask your own →';
    link.addEventListener('click', (e) => {
      e.preventDefault();
      composerQ.focus();
    });
  } else {
    // Clears the fragment and returns to the live app (a full reload to a clean
    // URL — no share state, fresh session).
    link.href = location.pathname;
    link.textContent = 'ask your own live question →';
  }
  el.appendChild(lead);
  el.appendChild(document.createTextNode(' '));
  el.appendChild(link);
}

// Restore a full answer view from a decoded permalink — no agent run, no key.
// Reuses the live render paths (renderChart / renderTable / renderCitations),
// all of which write text via textContent or escape through esc() before any
// innerHTML, so nothing from the payload is ever injected as markup.
//
// Also the play path for a shipped demo (mode 'demo'): a demo IS this same
// frozen state, so it renders through this one function rather than a parallel
// implementation — the example a visitor sees is therefore, structurally, the
// real thing (same chart, same evidence table, same citation ledger, same CSV).
export async function restoreSharedAnswer(state: ShareStateV1, mode: RestoreMode = 'shared') {
  const tb = createTurnBlock();
  tb.isShared = true;
  tb.question = state.q;
  allTurns.push(tb);
  renderShareBanner(tb, state, mode);
  renderQuestion(tb, state.q);
  // No trace panel on a shared view (there is no run to show).
  if (state.spec) {
    liveChartTurns.push(tb); // keep it re-theming/resizing like a live chart
    tb.canvasEl.classList.remove('ch-canvas-pending');
    // The chart is the ONLY part of this view that needs the network: ECharts
    // is a CDN import. A blocked CDN (corporate proxy, content blocker, plain
    // offline) must not cost the reader the answer, the evidence table and the
    // citations, which are all already in hand — and it must not be reported as
    // a bad link/demo, which is what an escaping throw did. So: render the
    // chart best-effort, say plainly when it couldn't load, and carry on.
    try {
      await renderChart(tb, state.spec);
    } catch (err) {
      console.error('chart render failed', err);
      renderChartUnavailable(tb, state.spec.title);
    }
    tb.renderFlag.style.display = 'none';
  }
  tb.answerSection.style.display = 'block';
  tb.metaSection.style.display = 'block';
  renderFinding(tb, state.answer);
  renderSharedVerification(tb, state.verification);
  renderTable(tb, state.rows, rowsToCSV(state.rows));
  renderCitations(tb, state.citations);
  // Hide the setup console and switch the composer to "new conversation".
  consoleEl.style.display = 'none';
  newConvoBtn.style.display = '';
  composerQ.placeholder = 'Ask your own live question…';
}

// The chart library didn't load. Keep the card (so the layout doesn't jump and
// the reader still learns what the chart WOULD have shown) and state the reason
// in place of the canvas. Text only — never a retry that could loop.
export function renderChartUnavailable(tb: TurnBlock, title: string) {
  tb.chartTitle.textContent = title;
  tb.chartUnit.textContent = '';
  tb.chartEl.removeAttribute('role');
  tb.chartEl.textContent = 'Chart unavailable — the chart library could not be loaded. The numbers below are unaffected.';
  tb.chartEl.classList.add('ch-chart-fallback');
}

export function renderShareError() {
  consoleEl.style.display = 'none';
  const tb = createTurnBlock();
  allTurns.push(tb);
  const el = tb.shareBanner;
  el.style.display = 'block';
  el.classList.add('ch-share-banner-error');
  el.textContent = '';
  const lead = document.createElement('span');
  lead.className = 'ch-share-banner-lead';
  lead.textContent = 'This share link is invalid — it may be corrupted, truncated, or from a newer version.';
  const link = document.createElement('a');
  link.className = 'ch-share-banner-link';
  link.href = location.pathname;
  link.textContent = 'ask your own live question →';
  el.appendChild(lead);
  el.appendChild(document.createTextNode(' '));
  el.appendChild(link);
}

// Invalid #dash= link: open the dashboards overlay showing a clear error and a
// way back to the live app. No tiles, no controls — never a half-rendered view.
export function renderDashShareError() {
  resetSharedDashState();
  consoleEl.style.display = 'none';
  dashView.hidden = false;
  document.body.classList.add('ch-dashview-open');
  dashViewTitle.textContent = 'Shared dashboard';
  dashViewBack.setAttribute('aria-label', 'Leave shared dashboard');
  dashViewBody.innerHTML = '';
  const banner = document.createElement('div');
  banner.className = 'ch-share-banner ch-share-banner-error ch-dash-shared-banner';
  banner.setAttribute('role', 'note');
  banner.setAttribute('data-testid', 'dash-share-error');
  const lead = document.createElement('span');
  lead.className = 'ch-share-banner-lead';
  lead.textContent = 'This shared dashboard link is invalid — it may be corrupted, truncated, or from a newer version.';
  const link = document.createElement('a');
  link.className = 'ch-share-banner-link';
  link.href = location.pathname;
  link.textContent = 'open the live app →';
  banner.appendChild(lead);
  banner.appendChild(document.createTextNode(' '));
  banner.appendChild(link);
  dashViewBody.appendChild(banner);
  requestAnimationFrame(() => dashViewBack.focus());
}

// On load, if the URL carries a #share= fragment, restore that answer view
// instead of the empty app. Defensive: any decode failure shows a clear
// invalid-link state and never crashes the page or executes payload content.
export async function maybeRestoreFromFragment() {
  const hash = location.hash || '';
  // A URL carries only ONE of these fragments. #share= restores an answer view;
  // #dash= restores a read-only shared dashboard. Distinct prefixes, checked in
  // order; neither ever reaches a server (both are fragments).
  const share = hash.match(/^#share=(.+)$/);
  if (share) {
    let state: ShareStateV1 | null = null;
    try {
      state = await decodeShareState(decodeURIComponent(share[1]));
    } catch {
      state = null;
    }
    if (!state) { renderShareError(); return; }
    try {
      await restoreSharedAnswer(state);
    } catch (err) {
      console.error('share restore failed', err);
      renderShareError();
    }
    return;
  }
  const dash = hash.match(/^#dash=(.+)$/);
  if (dash) {
    let state: DashShareV1 | null = null;
    try {
      state = await decodeDashShare(decodeURIComponent(dash[1]));
    } catch {
      state = null;
    }
    if (!state) { renderDashShareError(); return; }
    try {
      consoleEl.style.display = 'none';
      renderSharedDashboard(state);
      requestAnimationFrame(() => dashViewBack.focus());
    } catch (err) {
      console.error('dashboard share restore failed', err);
      renderDashShareError();
    }
  }
}
