import { describe, expect, it, vi } from 'vitest';
import { createJevAssist } from './jev';
const hits = [{id:'A',name:'GDP current dollars',source:'worldbank'},{id:'B',name:'GDP per capita',source:'worldbank'}];
const routeAnswer = (choice='candidate_1', probability=.95) => ({answers:{dataset:{type:'choice',choice,probabilities:Object.fromEntries([...Array.from({length:8},(_,i)=>`candidate_${i}`),'none'].map(k=>[k,k===choice?probability:k==='none'?1-probability:0]))}}});
const checks = ['answers_question','supported_by_data','sources_match','chart_matches_data','no_overclaim'];
const reviewAnswer = (p=.97) => ({answers:Object.fromEntries(checks.map(id=>[id,{type:'noul',noul:p}]))});
const evidence = {question:'GDP per capita in India in 2020?',finding:'India: 2000 dollars in 2020.',spec:{type:'bar' as const,title:'GDP per capita',series:[{name:'India',data:[[2020,2000] as [number,number]]}]},rows:[{country:'India',iso3:'IND',year:2020,value:2000,indicator:'B'}],citations:[{source:'worldbank' as const,sourceLabel:'World Bank',indicatorId:'B',indicatorName:'GDP per capita',url:'https://data.worldbank.org/indicator/B'}]};
function setup(answer:unknown) { const fetcher=vi.fn(async(_input: RequestInfo | URL, _init?: RequestInit)=>Response.json({response:answer,latency_ms:12}));return {fetcher,client:createJevAssist({base:'https://example.test',fetch:fetcher})}; }
describe('Jev assist',()=>{
 it('promotes only a supplied candidate and preserves every hit',async()=>{const {client,fetcher}=setup(routeAnswer());const out=await client.route('GDP per capita',hits);expect(out.hits.map(h=>h.id)).toEqual(['B','A']);expect(hits[0].id).toBe('A');expect(out.report).toContain('95%');expect(JSON.parse(fetcher.mock.calls[0][1]!.body as string).task).toBe('chitti_route');});
 it('keeps search order for uncertain, abstained, missing, and malformed selections',async()=>{for(const response of [routeAnswer('candidate_1',.6),routeAnswer('none',1),routeAnswer('candidate_7'),{answers:{}}]){const {client}=setup(response);expect((await client.route('GDP',hits)).hits).toEqual(hits);}});
 it('caps routing attempts and makes no request for empty candidates',async()=>{const {client,fetcher}=setup(routeAnswer());await client.route('GDP',[]);for(let i=0;i<4;i++)await client.route('GDP',hits);expect(fetcher).toHaveBeenCalledTimes(2);});
 it('never reports a provider or quota failure as successful verification',async()=>{const fetcher=vi.fn(async()=>new Response('private detail',{status:429,headers:{'Retry-After':'60'}}));const client=createJevAssist({base:'https://example.test',fetch:fetcher});expect((await client.route('GDP',hits)).hits).toEqual(hits);const out=await client.review(evidence);expect(out.status).toBe('unavailable');expect(out.pass).toBe(false);expect(out.report).not.toContain('private detail');});
 it('passes only when every focused check meets the threshold, with visible probabilities',async()=>{const {client,fetcher}=setup(reviewAnswer());const out=await client.review(evidence);expect(out.status).toBe('verified');expect(out.engine).toBe('jev');expect(out.report).toContain('supported_by_data');expect(out.report).toContain('0.97');const sent=JSON.parse(fetcher.mock.calls[0][1]!.body as string);expect(JSON.parse(sent.inputs.evidence).rows).toEqual(evidence.rows);});
 it('flags low evidence support without inventing a reason from the model',async()=>{const answer=reviewAnswer();answer.answers.supported_by_data.noul=.2;const {client}=setup(answer);const out=await client.review(evidence);expect(out.status).toBe('unverified');expect(out.issues.join(' ')).toContain('20%');expect(out.pass).toBe(false);});
 it('fails closed for missing or oversized evidence without spending a call',async()=>{const {client,fetcher}=setup(reviewAnswer());expect((await client.review({...evidence,rows:[]})).pass).toBe(false);expect((await client.review({...evidence,rows:Array(1000).fill(evidence.rows[0])})).status).toBe('unavailable');expect(fetcher).not.toHaveBeenCalled();});
 it('rejects incomplete model answers and limits review to two attempts',async()=>{const {client,fetcher}=setup({answers:{}});for(let i=0;i<3;i++)expect((await client.review(evidence)).pass).toBe(false);expect(fetcher).toHaveBeenCalledTimes(2);});
 it('honors cancellation without sending a request',async()=>{const fetcher=vi.fn();const controller=new AbortController();controller.abort();const client=createJevAssist({base:'https://example.test',fetch:fetcher},controller.signal);await expect(client.route('GDP',hits)).rejects.toThrow();expect(fetcher).not.toHaveBeenCalled();});
});
