// Generates public/favicon.svg from the learned weight matrix of a
// character-bigram name model trained at build time.
// The favicon is literally what the model knows about names.
//
// Run: node scripts/generate-favicon.mjs

import { writeFileSync } from 'node:fs';

const NAMES = 'emma,olivia,ava,isabella,sophia,charlotte,mia,amelia,harper,evelyn,abigail,emily,elizabeth,mila,ella,avery,sofia,camila,aria,scarlett,victoria,madison,luna,grace,chloe,penelope,layla,riley,zoey,nora,lily,eleanor,hannah,lillian,addison,aubrey,ellie,stella,natalie,zoe,leah,hazel,violet,aurora,savannah,audrey,brooklyn,bella,claire,skylar,lucy,paisley,everly,anna,caroline,nova,genesis,emilia,kennedy,samantha,maya,willow,kinsley,naomi,aaliyah,elena,sarah,ariana,allison,gabriella,alice,madelyn,cora,ruby,eva,serenity,autumn,adeline,hailey,gianna,valentina,isla,eliana,quinn,ivy,sadie,piper,lydia,alexa,josephine,emery,julia,delilah,arianna,vivian,kaylee,sophie,brielle,madeline'.split(',');

const V = 27; // boundary + a-z
const idx = (c) => (c === '.' ? 0 : c.charCodeAt(0) - 96);

// Deterministic PRNG so the favicon is reproducible build to build
let seed = 42;
function rng() {
  seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
  return seed / 4294967296;
}

const pairs = [];
for (const name of NAMES) {
  const w = '.' + name + '.';
  for (let i = 0; i < w.length - 1; i++) pairs.push([idx(w[i]), idx(w[i + 1])]);
}

const W = new Float64Array(V * V);
function rowProbs(a) {
  const p = new Float64Array(V);
  let mx = -Infinity;
  for (let j = 0; j < V; j++) mx = Math.max(mx, W[a * V + j]);
  let sum = 0;
  for (let j = 0; j < V; j++) { p[j] = Math.exp(W[a * V + j] - mx); sum += p[j]; }
  for (let j = 0; j < V; j++) p[j] /= sum;
  return p;
}

// 400 steps, batch 64, lr 0.5
for (let step = 0; step < 400; step++) {
  for (let b = 0; b < 64; b++) {
    const [a, t] = pairs[(rng() * pairs.length) | 0];
    const p = rowProbs(a);
    for (let j = 0; j < V; j++) W[a * V + j] -= 0.5 * (p[j] - (j === t ? 1 : 0));
  }
}

// Render: 27x27 transition-probability heatmap, amber on graphite.
// Row = current character, column = P(next character).
const cells = [];
for (let a = 0; a < V; a++) {
  const p = rowProbs(a);
  const rowMax = Math.max(...p);
  for (let j = 0; j < V; j++) {
    const v = p[j] / rowMax; // per-row normalization keeps every row's structure visible
    if (v < 0.06) continue;
    const o = (0.22 + 0.78 * Math.sqrt(v)).toFixed(2);
    cells.push(`<rect x="${j}" y="${a}" width="1" height="1" fill="#d9a13b" opacity="${o}"/>`);
  }
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 27">
<!-- The learned transition matrix of a character-bigram name model: row = current letter, column = P(next letter). Generated by scripts/generate-favicon.mjs -->
<clipPath id="r"><rect width="27" height="27" rx="3.5"/></clipPath>
<g clip-path="url(#r)">
<rect width="27" height="27" fill="#0b0d0c"/>
${cells.join('\n')}
</g>
</svg>
`;

writeFileSync(new URL('../public/favicon.svg', import.meta.url), svg);
console.log(`favicon.svg written: ${cells.length} cells (of ${V * V})`);
